#!/bin/bash

export ACKLEY_SLACK_API_TOKEN="<PUT SLACK API TOKEN HERE>"
export ACKLEY_BOTNAME="<PUT BOTNAME HERE>"
export ACKLEY_BOTID="<PUT BOTID HERE>"
export ACKLEY_WEBSOCKET_ORIGIN="http://localhost"
